name: Build and Test

on:
  workflow_call:

jobs:
  build-and-tests:
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run build
        run: bun run build

      - name: Run tests
        run: bun test --timeout 10000
