name: Publish the minor release

on:
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - name: "Build and test"
        uses: ./.github/actions/build-and-test

  publish-minor-release:
    needs: [build-and-test]
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          scope: "@runtimeverificationinc"
      - name: Set up Git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
      - name: Install dependencies
        run: |
          bun install --frozen-lockfile
      - name: Build the project
        run: |
          bun run build
      - name: Bump version
        run: |
          npm version minor
      - name: Publish version to GitHub
        run: |
          git push origin --follow-tags
      - name: Publish to npm
        run: |
          npm publish --access public --tag ${{ github.head_ref }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.RV_NPM_DEPLOY_TOKEN}}
