name: Pull Request tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: "Build and test"
        uses: ./.github/actions/build-and-test
